# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b69ea028a2add2ee2e97d9640dc658bd5b5ba0c36e4c958e8d7aa689204c74fe63a2e5fed94776ad52831828c6f355faeb8baf28d9f51a36ad9c42aea56e1e

test:
  secret_key_base: 913465a0ae9e478c91b1a0a018ca6c7b08a39131a5486b100cbbe2e4bbfe43912029158712d18dc56d6afcd1c86f628c20071f9e4655bf5a7e8f929cadd63662

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
